### ISSUE TITLE
What should be the name for Simplified DLL?

### ISSUE THREAD

**Issue by alemoi** [Polyjuice/Simplified#2]
Since we are putting current Simplified.dll to distribution, I guess the name for this DLL should be different, since its something people are going to add as a library reference in Visual Studio, etc.

**Comment by warpech** [comment]
How about "Simplified Data Model"?

**Comment by dan31** [comment]
Should it be in some "Models" namespace, like "Starcounter.Models.Simplified"?

**Comment by warpech** [comment]
I think that the idea was to emphasise this is something arbitrary that did not come from Starcounter. 

Like "ContosoUniversity" is not in "Microsoft" namespace.

**Comment by alemoi** [comment]
Maybe then Polyjuice.Ontology.Simplified? Or Models instead of Ontology, like you proposed.

**Comment by warpech** [comment]
do you need it to be in a namespace? I thought this question was only about the filename.

if we put it in a namespace then it will get very Java-ish: `Polyjuice.Ontology.Simplified.Ring1.Person`

**Comment by alemoi** [comment]
No, it wasn't about namespace. I was thinking about the situation when user adds it as a DLL reference in Visual Studio, so its should start with some known prefix.

**Comment by warpech** [comment]
Ah, sorry. But usually the name in the references list matches the namespace, doesn't it?

It cannot be "Polyjuice" because it would suggest that this is an endorsed component and it is not. It is just some arbitrary data model we created for the sake of the demo apps.

How about Sample.Model.Simplified?

**Comment by alemoi** [comment]
Ok, I see then. I just thought this one is endorsed :)

**Comment by alemoi** [comment]
Thanks for responses. I will name it `Sample.Model.Simplified` for now.

**Comment by alemoi** [comment]
Sorry, I will rename it to your first variant `Simplified.Data.Model.dll` :)

**Comment by alemoi** [comment]
Fixed now that `Simplified.Data.Model.dll` is a part of distribution. Known Polyjuice applications are updated correspondingly.
